///generated by http://jsongen.byingtondesign.com/
package yelp;

import java.util.List;

public class Business_Prof{
   	private String business_id;
   	private List<String> categories;
   	private String city;
   	private String full_address;
   	private Number latitude;
   	private Number longitude;
   	private String name;
   	private List<String> neighborhoods;
   	private boolean open;
   	private String photo_url;
   	private Number review_count;
   	private List<String> schools;
   	private Number stars;
   	private String state;
   	private String type;
   	private String url;

 	public String getBusiness_id(){
		return this.business_id;
	}
	public void setBusiness_id(String business_id){
		this.business_id = business_id;
	}
 	public List<String> getCategories(){
		return this.categories;
	}
	public void setCategories(List<String> categories){
		this.categories = categories;
	}
 	public String getCity(){
		return this.city;
	}
	public void setCity(String city){
		this.city = city;
	}
 	public String getFull_address(){
		return this.full_address;
	}
	public void setFull_address(String full_address){
		this.full_address = full_address;
	}
 	public Number getLatitude(){
		return this.latitude;
	}
	public void setLatitude(Number latitude){
		this.latitude = latitude;
	}
 	public Number getLongitude(){
		return this.longitude;
	}
	public void setLongitude(Number longitude){
		this.longitude = longitude;
	}
 	public String getName(){
		return this.name;
	}
	public void setName(String name){
		this.name = name;
	}
 	public List<String> getNeighborhoods(){
		return this.neighborhoods;
	}
	public void setNeighborhoods(List<String> neighborhoods){
		this.neighborhoods = neighborhoods;
	}
 	public boolean getOpen(){
		return this.open;
	}
	public void setOpen(boolean open){
		this.open = open;
	}
 	public String getPhoto_url(){
		return this.photo_url;
	}
	public void setPhoto_url(String photo_url){
		this.photo_url = photo_url;
	}
 	public Number getReview_count(){
		return this.review_count;
	}
	public void setReview_count(Number review_count){
		this.review_count = review_count;
	}
 	public List<String> getSchools(){
		return this.schools;
	}
	public void setSchools(List<String> schools){
		this.schools = schools;
	}
 	public Number getStars(){
		return this.stars;
	}
	public void setStars(Number stars){
		this.stars = stars;
	}
 	public String getState(){
		return this.state;
	}
	public void setState(String state){
		this.state = state;
	}
 	public String getType(){
		return this.type;
	}
	public void setType(String type){
		this.type = type;
	}
 	public String getUrl(){
		return this.url;
	}
	public void setUrl(String url){
		this.url = url;
	}
}
