//generated by http://jsongen.byingtondesign.com/
package yelp;


public class User_Prof{
   	private Number average_stars;
   	private String name;
   	private Number review_count;
   	private String type;
   	private String url;
   	private String user_id;
   	private Votes votes;

 	public Number getAverage_stars(){
		return this.average_stars;
	}
	public void setAverage_stars(Number average_stars){
		this.average_stars = average_stars;
	}
 	public String getName(){
		return this.name;
	}
	public void setName(String name){
		this.name = name;
	}
 	public Number getReview_count(){
		return this.review_count;
	}
	public void setReview_count(Number review_count){
		this.review_count = review_count;
	}
 	public String getType(){
		return this.type;
	}
	public void setType(String type){
		this.type = type;
	}
 	public String getUrl(){
		return this.url;
	}
	public void setUrl(String url){
		this.url = url;
	}
 	public String getUser_id(){
		return this.user_id;
	}
	public void setUser_id(String user_id){
		this.user_id = user_id;
	}
 	public Votes getVotes(){
		return this.votes;
	}
	public void setVotes(Votes votes){
		this.votes = votes;
	}
}
