//generated by http://jsongen.byingtondesign.com/
package yelp;


public class Votes{
   	private Number cool;
   	private Number funny;
   	private Number useful;

 	public Number getCool(){
		return this.cool;
	}
	public void setCool(Number cool){
		this.cool = cool;
	}
 	public Number getFunny(){
		return this.funny;
	}
	public void setFunny(Number funny){
		this.funny = funny;
	}
 	public Number getUseful(){
		return this.useful;
	}
	public void setUseful(Number useful){
		this.useful = useful;
	}
}
